export const countriesAndRegions = {
	Argentina: [
		'Buenos Aires',
		'Catamarca',
		'Chaco',
		'Chubut',
		'Córdoba',
		'Corrientes',
		'Entre Ríos',
		'Formosa',
		'Jujuy',
		'La Pampa',
		'La Rioja',
		'Mendoza',
		'Misiones',
		'Neuquén',
		'Río Negro',
		'Salta',
		'San Juan',
		'San Luis',
		'Santa Cruz',
		'Santa Fe',
		'Santiago del Estero',
		'Tierra del Fuego',
		'Tucumán',
		'Ciudad Autónoma de Buenos Aires',
	],
	Brasil: [
		'Acre',
		'Alagoas',
		'Amapá',
		'Amazonas',
		'Bahia',
		'Ceará',
		'Distrito Federal',
		'Espírito Santo',
		'Goiás',
		'Maranhão',
		'Mato Grosso',
		'Mato Grosso do Sul',
		'Minas Gerais',
		'Pará',
		'Paraíba',
		'Paraná',
		'Pernambuco',
		'Piauí',
		'Rio de Janeiro',
		'Rio Grande do Norte',
		'Rio Grande do Sul',
		'Rondônia',
		'Roraima',
		'Santa Catarina',
		'São Paulo',
		'Sergipe',
		'Tocantins',
	],
	Chile: [
		'Arica y Parinacota',
		'Tarapacá',
		'Antofagasta',
		'Atacama',
		'Coquimbo',
		'Valparaíso',
		'Región Metropolitana de Santiago',
		"O'Higgins",
		'Maule',
		'Ñuble',
		'Biobío',
		'La Araucanía',
		'Los Ríos',
		'Los Lagos',
		'Aysén',
		'Magallanes y de la Antártica Chilena',
	],
	Colombia: [
		'Amazonas',
		'Antioquia',
		'Arauca',
		'Atlántico',
		'Bogotá D.C.',
		'Bolívar',
		'Boyacá',
		'Caldas',
		'Caquetá',
		'Casanare',
		'Cauca',
		'Cesar',
		'Chocó',
		'Córdoba',
		'Cundinamarca',
		'Guainía',
		'Guaviare',
		'Huila',
		'La Guajira',
		'Magdalena',
		'Meta',
		'Nariño',
		'Norte de Santander',
		'Putumayo',
		'Quindío',
		'Risaralda',
		'San Andrés y Providencia',
		'Santander',
		'Sucre',
		'Tolima',
		'Valle del Cauca',
		'Vaupés',
		'Vichada',
	],
}
